import './showMarks.js'
import './integrations/ServicesIterating.js'
import './integrations/AboutUsIntegration.js'
import './integrations/PricePagination.js'
import './modals/fillForm.js'
import './modals/popup.js'
import './scrollToSection.js'
import './burger.js'